### ISSUE TITLE
Suggestion, return an named array

### ISSUE THREAD

**Issue by orjanalmen** [paragonie/easydb#100]
This seems like a great library!

What I feel could easily be added would be a function that delivers an ready array, Something to replace
```
$rows = $easydb->run();
foreach ($rows as $row) {
    $arr[$row[$keyfield]] = $row[$valuefield];
}
```

As a second suggestion, an array with a row key and all the other fields as rows in the array, that would replace 
```
$rows = $easydb->run();
foreach ($rows as $row) {
    $arr[$row[$keyfield]] = $row;
}
```

**Comment by paragonie-security** [comment]
This is basically a request to add a CSV mapping to the output, right?

Unfortunately, there is no elegant way to do this with PDO, so you'd need a helper function.

```php
<?php

function toCSV(array $results): array
{
    $mapping = [];
    array_push($mapping, array_keys($results[0]));
    foreach ($results as $row) {
        array_push($mapping, array_values($row));
    }
    return $mapping;
}
```
