### ISSUE TITLE
Column Name

### ISSUE THREAD

**Issue by jjokham** [paragonie/easydb#101]
Are there any security risks if the form field name and mysql database column names are identical ?

**Comment by paragonie-scott** [comment]
This sort of question is [XY problem](http://xyproblem.info/) territory.

Are you letting users arbitrary provide column names? Then that would be a security risk.

Are they just coincidentally the same string? Then no.

**Comment by jjokham** [comment]
Hi Scott,
Thank you for the reply. 
Adding more context. 

I am creating a stripe like functionality for database CRUD operations. That is, a web developer defines the table and column names in data- attributes (eg. data-tablename, data-columname) for his/her form or input fields,  adds my script tag to handle events and data collection. On the backend developer makes a curl call to my application (with api key) for authentication. In order to make this simple i am allowing table and column names to be defined in the data attributes. I  add a csrf token on the user page and a hashed signature in the session storage for verifying integrity. 
Just wanted to know if this is a stupid idea. But, I find it frustrating that so many man hours are wasted trying to save forms or fields in database. There has to be an easier and secured way. 
Would love to hear your thoughts as an expert.
Again, thank you for the awesome advice on php security.
