### ISSUE TITLE
Composer version Installation 

### ISSUE THREAD

**Issue by jjokham** [paragonie/easydb#103]
When I use composer require paragonie/easydb:^2, it installs 2.0.0. 
2.0.0 does not allow me to connect to my database. But, after forcing 2.8.0, with the same code I am able to connect to my database.

**Comment by paragonie-scott** [comment]
That's weird. It should install the latest version of the 2.x branch (i.e. 2.8.0).

https://getcomposer.org/doc/articles/versions.md#writing-version-constraints

**Comment by paragonie-scott** [comment]
Check your other dependencies. They might be forcing it to a lower version.

Worst case scenario:

```json
{
    "require": {
        "paragonie/easydb": ">=2.9.0 <3"
    }
}
```

**Comment by troyporter** [comment]
Having the same issue here using the installation instructions - composer seems to install v2.0.0 where the fromArray method isn't available.

Even when i try:

`{
    "require": {
        "paragonie/easydb": ">=2.9.0 <3"
    }
}`
