### ISSUE TITLE
How to run trigger queries

### ISSUE THREAD

**Issue by jjokham** [paragonie/easydb#109]
how can you run trigger queries. I get the following error.
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. 
I have tried with and without using delimiter statements and it still did not work. 

```
   $triggerquery = " CREATE TRIGGER `$triggername` $triggertime ON `$tablename` 
							FOR EACH ROW 
							BEGIN 
								IF(NEW.`$triggercol` IS NULL) 
								THEN 
									SET NEW.`$triggercol` = UNIX_TIMESTAMP(); 
								END IF; 
							END;
						";
```

**Comment by fredricj** [comment]
The error you get usually occurs when you already have an query for which you haven't closed the cursor yet. If that is not the case provide a minimal working example producing this error.
