### ISSUE TITLE
`insertReturnId` is missing the return type

### ISSUE THREAD

**Issue by gnif** [paragonie/easydb#117]
According to the documentation `insertReturnId` should return an `int` however PDO returns a int in a string. The fix is simple, add `: int` to the end of the function defenition and typecasting the result of `lastInsertID`

https://github.com/paragonie/easydb/blob/69abc6b7393b0e0bc7fca6b800909c8d7906b3b2/src/EasyDB.php#L658

**Comment by paragonie-scott** [comment]
You aren't always guaranteed that you're going to return an integer. Some tables use UUID primary keys, which would return a string instead of an integer, which means `insertGetId()` is not compatible with an `int` return type.

**Comment by gnif** [comment]
Ah true, understood, thanks!
