### ISSUE TITLE
Inserting a null value

### ISSUE THREAD

**Issue by isaac-bacon-simplyphp** [paragonie/easydb#121]
Is there some kind of way to insert a null value in a nullable column? Such as a constant like EasyDB::NULL_VALUE? I tried inserting with the insert() function something like ['start_date' => null] and ['start_date' => 'null'] and ['start_date' => 'NULL'] and ['start_date' => NULL] and ['start_date' => '']. Usually, most ORM's have that value as a constant.

**Comment by paragonie-security** [comment]
You just pass a `null` value as you'd expect.

```php
$easyDb->insert('table_name', [
    'column1' => 'something',
    'column2' => null,
    'column3' => false
]);
