### ISSUE TITLE
weird error using EasyDB

### ISSUE THREAD

**Issue by Aranjedeath** [paragonie/easydb#125]
I have all the debugging stuff in PHP turned on so if there are ever notices, even, it spews into logs.

Today, this showed up, which is very interesting to me. I did not know easydb uses guzzle? Elsewhere in my project guzzle is used (dependency of another library in use). This is a fresh composer install of EasyDB, which composer tells me is v2.11.0

Recoverable fatal error: Object of class GuzzleHttp\Psr7\Response could not be converted to string in /path/to/app/includes/vendor/paragonie/easydb/src/EasyDB.php on line 1005

**Comment by paragonie-security** [comment]
EasyDB doesn't.

https://github.com/paragonie/easydb/blob/38cfac4bbd96960628ca3237ed98f3f344ffdd7b/composer.json#L48-L58

It's more than likely that something is passing a `Response` object to an EasyDB method and it's being passed to `PDOStatement::execute()`.

https://github.com/paragonie/easydb/blob/v2.11.0/src/EasyDB.php#L1005

**Comment by Aranjedeath** [comment]
Ah! OK, thank you. 

somewhere I am calling a database and my argument is not what it seems
