### ISSUE TITLE
Last Insert ID?

### ISSUE THREAD

**Issue by ritziyap** [paragonie/easydb#126]
Anyone knows how to get the LAST INSERT ID?

**Comment by kerframil** [comment]
`$db->getPdo()->lastInsertId()`

**Comment by paragonie-security** [comment]
You can short-circuit this by just saying `$db->lastInsertId()`.

Alternatively, you can use `insertGet()` to select the auto-generated value for a given column at insert time in one API call. (Some database drivers don't support `lastInsertId()` correctly.)
