### ISSUE TITLE
Getting an error during the connection

### ISSUE THREAD

**Issue by ARACOOOL** [paragonie/easydb#128]
Version: 2.0.0
PHP: 7.3

Error message:
```
 Trying to clone an uncloneable object of class PDO in .../vendor/paragonie/easydb/src/EasyDB.php:37
```

**Comment by dafriend** [comment]
You need to update to a newer version. [v2.0.1](https://github.com/paragonie/easydb/blob/v2.0.1/CHANGELOG.md#version-201---2016-10-18) fixed this issue.
