### ISSUE TITLE
is this class support php version 5.6

### ISSUE THREAD

**Issue by ihaideri** [paragonie/easydb#145]
Hi,

I am thinking to use this class for my old built website code PHP MySQL based website
its developed in PHP version 5.6
can we use this EasyDB as MySQL wrapper class?
please advise.

Thanks
Imran

**Comment by paragonie-security** [comment]
The v1.x branch supports PHP 5.6, yes. https://github.com/paragonie/easydb/blob/v1.x-legacy/composer.json#L46
