### ISSUE TITLE
select in(...)

### ISSUE THREAD

**Issue by Lewiscowles1986** [paragonie/easydb#2]
What protections does this offer for `SELECT blah FROM blah  WHERE blah IN($injected)`

type queries

**Comment by paragonie-scott** [comment]
None. You need an ORM, etc. for something like that.

**Comment by Lewiscowles1986** [comment]
Can I PR one? I think I can come up with a pretty good, secure solution

**Comment by paragonie-scott** [comment]
Of course, feel free.

**Comment by Lewiscowles1986** [comment]
Quick question

would you prefer I converted ` IN(?)` with an array as param into ` IN(?,?,?)`... or simply replaced ` IN(?)` with ` IN(x,y,z)`?

I'm thinking the later, using a utility function like the following

```php
    public function build_in(array $values, $type=\PDO::PARAM_STR, $filter=null)
    {
        $vals = [];
        $vals = (array)$values;
        
        // allow user-customisable filter for values
        if (is_callable($filter)) {
            $vals = array_filter($values, $filter);
        }
        
        $quote = function($val) use($type) { return $this->quote($val, $type); };
        $vals = array_map($quote->bindTo($this), $vals);
        $valstr = implode(',', $vals);
        return "IN({$valstr})";
    }
```

but I am unsure how robust PDO quote method is. I think whatever is chosen the ability to supply a filter or filters would help application developer(s) to ensure that their data is correctly filtered for the `IN` clause.

Thoughts on this approach?

**Comment by PeeHaa** [comment]
Imo if you want something like this in you should use proper parameters. This removes the burden of manually quoting (instant win) and just letting the engine handle it properly.

**Comment by Lewiscowles1986** [comment]
Thank you @PeeHaa :+1:  this was a thought of mine also, I'll get to work in the new week :wink:

**Comment by PeeHaa** [comment]
I think you should drop the filter parameter. If something needs a filter it's a separate responsibility.

**Comment by Lewiscowles1986** [comment]
right I have a function I made on a break from work today. It does the job and has passed the limited tests I have put it through, but it highlights to me, that possibly it should not be part of the library, and that we should instead use filters on the query, and values before binding and sending to the database.

```php
function transform_in(array $values, $sqlString) {
    if( stripos($sqlString,' IN(') !== FALSE ) {
        $sqlStrings = \explode("?", $sqlString);

        $mapPlaceholders = function($i, $sStr) use ($values) {
            $val = '';
            if($i < \count($values)-1) {
                $val = $values[$i];
            }
            if(\stripos($sStr,' IN(') === \strlen($sStr)-4) {
                $vals = (array)$values[$i];
                // build placeholders
                $out = \implode(
                   ', ',
                    \array_fill(0, \count($vals), '?')
                );
                // return modified entries containing the IN clause for their position at their position (should always be $i+1)
                return "{$sStr}{$out}";
            }
            return (\strlen($sStr) > 2) ? "{$sStr}?" : $sStr;
        };
        // use array map to add in placeholders ("?")
        $sqlStrings = \array_map( 
            $mapPlaceholders,
            \array_keys($sqlStrings),
            $sqlStrings
        );
        //var_dump($sqlStrings);
        $sqlString = \implode("", $sqlStrings);
        // time to flatten values by one level only
        $out = [];
        $evilMap = function($v) use (&$out) {
            if(!\is_array($v)) {
                $out[] = $v;
            } else {
                foreach($v as $vi) {
                    $out[] = $vi;
                }
            }
            return $v;
        };
        \array_map( $evilMap, $values);
        $values = $out;
    }
    return [$values,$sqlString];
}
```

**Comment by Lewiscowles1986** [comment]
Basically it looks like it would benefit from being a class of it's own

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/easydb/blob/d9bd0b6a70e7d76a026542ac3a34743d32770ec1/src/EasyDB.php#L164-L221

Be very careful with using this.
