### ISSUE TITLE
EasyStatement: Support Joins

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/easydb#20]
Before I release v2.1.0 and v1.1.0 I intend to add support for JOINs:

* `JOIN`
* `LEFT JOIN`

I'm tackling this tonight.

**Comment by paragonie-scott** [comment]
Oh, I see. This is only meant to follow `WHERE` clauses.

**Comment by matneves** [comment]
Hey, sorry to reopen such an old issue. Have you worked on something to make joins in a more generic way? Something like:

```
$userData = $db->row(
  "SELECT articles.title, users.name FROM users WHERE userid = ?",
  $_GET['userid']
)->join('articles', 'articles.userid');
```

**Comment by shadowhand** [comment]
You might want to check out Latitude if you're looking for a query builder. https://github.com/shadowhand/latitude
