### ISSUE TITLE
Version 1.1.0 contains PHP 7 hints

### ISSUE THREAD

**Issue by shadowhand** [paragonie/easydb#22]
The current 1.1.0 tag is not compatible with PHP 5.6. It looks identical to tag 2.1.0:

https://github.com/paragonie/easydb/compare/1.1.0...2.1.0

**Comment by paragonie-scott** [comment]
Hmm, I must've done something wrong.

**Comment by shadowhand** [comment]
Any idea when this will be fixed? It is blocking me from using EasyDB on a project.

**Comment by shadowhand** [comment]
Resolved by 29a42b71a2a7d4fdb6160b6cd626d133f3ca4432
