### ISSUE TITLE
Why not use PDO::ATTR_DRIVER_NAME?

### ISSUE THREAD

**Issue by shadowhand** [paragonie/easydb#23]
Currently in order to enable the correct quoting string, we need to pass `$dbEngine`. It looks like this code could be replaced with:

```php
if (empty($dbEngine)) {
  $dbEngine = $db->getAttribute(PDO::ATTR_DRIVER_NAME);
}
```

Any reason not to do this?

**Comment by paragonie-scott** [comment]
No reason not to do that. :)
