### ISSUE TITLE
automated tests broken on hhvm

### ISSUE THREAD

**Issue by SignpostMarv** [paragonie/easydb#24]
e84ed96ca2fe6c2d5ca41b890c22c836c998bcef reverts deb3a6905d5312c5814cb9c9f798a78a60f3b759 which stops tests from running on hhvm.

**Comment by shadowhand** [comment]
Sorry about that. This also relates to #22, since the current 1.1.0 release will so fail to install on PHP 5.x because of this change. I will revert and release 2.1.1 and 1.1.1.

**Comment by shadowhand** [comment]
@SignpostMarv will using `"php": ">=5.6.0"` work for HHVM?

**Comment by shadowhand** [comment]
Fixed and released in 2.1.1 and 1.1.1.
