### ISSUE TITLE
UTF8 vs utf8mb4

### ISSUE THREAD

**Issue by Lewiscowles1986** [paragonie/easydb#3]
is there any greater vulnerability to using utf8mb4 than utf8? Also will unicode automatically map to utf8mb4 for mysql / percona / mariadb?

How well does this work with other DBMS?

**Comment by Lewiscowles1986** [comment]
http://stackoverflow.com/questions/134099/are-pdo-prepared-statements-sufficient-to-prevent-sql-injection/12202218#12202218 suggests that if utf8 is forced (so no optional charset), then emulate prepares is no longer an issue (If I have understood correctly)

**Comment by paragonie-scott** [comment]
If you're using MySQL, use utf8mb4, not utf8.

**Comment by Lewiscowles1986** [comment]
I Just went through this looking for the reason I was even asking... I think it is this line 

https://github.com/paragonie/easydb/blob/master/src/Factory.php#L37

I'm unsure if it can even be utf8mb4 as it's the connection string. IDK we can close if helpful
