### ISSUE TITLE
Odd issue with 1D Array errors

### ISSUE THREAD

**Issue by Vansers** [paragonie/easydb#35]
So if I run this query...

> $db->run('SELECT * FROM `users` WHERE `userid`=? AND `first_name`=?', [1, 'Kyle'])

I get this message. As this is clear to me that I'm only passing a 1D array, but I'm not sure why this error keeps popping out.

Fatal error: Uncaught InvalidArgumentException: Only one-dimensional arrays are allowed. 
File: EasyDB.php:651

Any ideas?

**Comment by shadowhand** [comment]
The [`run()`](https://github.com/paragonie/easydb/blob/0a04e8d0efbd303df7280e70bffb3368e1ead2c3/src/EasyDB.php#L605) method uses a [variadic signature](https://wiki.php.net/rfc/variadics), so your code should look like:

```php
$db->run('SELECT * FROM users WHERE userid=? AND first_name=?', 1, 'Kyle');
```

If your parameters are already defined as an array, you can do:

```php
$db->run('SELECT * FROM users WHERE userid=? AND first_name=?', ... [1, 'Kyle']);
```

**Comment by paragonie-scott** [comment]
You also might be confused with `safeQuery()` which does expect an array. `run()` is the preferred way of doing things.

**Comment by Vansers** [comment]
I was @paragonie-scott haha. Thanks for your help guys! ;-).
