### ISSUE TITLE
Using LOAD DATA LOCAL INFILE with easydb

### ISSUE THREAD

**Issue by Vansers** [paragonie/easydb#38]
So, I have a text file with over 6 million lines of data, I have no options to use insert() as this leaks my server PHP memory as this takes almost 15 mins to import 6 millions rows. So I had to use the run() function to import the text file with load infile sql function but it tells me this...

> General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll() or setting PDO::MYSQL_ATTR_USE_BUFFERED_QUERY

Which I thought the run() function executes fetchAll() which it does, so I tried setting the buffer query with setAttribute() and it didn't work, same error, which left me another option to try...

> PDO::ATTR_EMULATE_PREPARES => true

Which I used to setAttribute(), and it tells me it doesn't allow the use of emulated prepared statements, which would be a security downgrade.

How can I use LOAD DATA LOCAL INFILE with easydb?

Thanks!

**Comment by shadowhand** [comment]
I would recommend using PDO directly for any kind of very specific database operation.
