### ISSUE TITLE
Using MySQL functions in insert() or update()

### ISSUE THREAD

**Issue by mignaulo** [paragonie/easydb#4]
Do you have thoughts on how this wrapper could be modified to safely allow MySQL functions as parameters when using `insert()` or `update()`? These two shortcuts are tremendously useful but not being able to use them with native MySQL functions restricts their use in some areas.

As an example, we have queries that make use of `NOW()` which would not use any parameter marker. We also have queries that make use of `NET_ATON(ip)` which would still use a parameter marker `?`

**Comment by paragonie-scott** [comment]
I would be very cautious about mixing the capability for "arbitrary MySQL functions" in prepared statements. Feel free to create triggers for this instead.

https://dev.mysql.com/doc/refman/5.7/en/create-trigger.html

**Comment by mignaulo** [comment]
For what it's worth, I ended up adding a `Literal()` class [here](https://github.com/mignaulo/easydb/blob/escape-table-identifier/src/Literal.php).
You can then do 
```
$fields = [
    "name" => $name,
    "ip" => new Literal("INET_ATON(?)", $ip_address)
];
$db->insert("table", $fields);
```
If you think that has any value, I'd be happy to submit a clean PR. I understand if you'd rather not include it though.

This same branch also has some changes that allow you to use `dbname.tablename` as the first argument of those shortcut functions. I'd be happy to submit a PR for that as well.
