### ISSUE TITLE
Sanitation / input validation

### ISSUE THREAD

**Issue by Jack-Rogers** [paragonie/easydb#46]
In your example you used $_GET to make a SQL statement, Does this mean that you also perform input sanitation?
`"SELECT * FROM comments WHERE blogpostid = {`**$_GET['blogpostid']**`} ORDER BY created ASC"`

**Comment by kelunik** [comment]
That's legacy code that's refactored and should obviously not be used.

**Comment by paragonie-scott** [comment]
This was never an example, it was a starting point.

The README has been cleaned up, and this snippet has been removed.
