### ISSUE TITLE
Allow more characters in field names

### ISSUE THREAD

**Issue by ponchofiesta** [paragonie/easydb#48]
I tried to use EasyDB with an in-memory sqlite DB with special field names in the table. EasyDB doesn't accept them. I changed allowSeperators to true but than it filters characters from my fieldlist and doesn't find it anymore. SQlite itself doesn't have problems with this.

To reproduce, try this:

```php
$db = \ParagonIE\EasyDB\Factory::create('sqlite::memory:');
php > $db->setAllowSeparators(true);
php > $db->run('create table test(`a/b` TEXT);'); // works
php > $db->insert('test', [ 'a/b' => "test" ]); // exception thrown
```
Causes:
```
Warning: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 table test has no column named ab in /usr/src/app/vendor/paragonie/easydb/src/EasyDB.php:641
Stack trace:
#0 /usr/src/app/vendor/paragonie/easydb/src/EasyDB.php(641): PDO->prepare('INSERT INTO "te...')
#1 /usr/src/app/vendor/paragonie/easydb/src/EasyDB.php(434): ParagonIE\EasyDB\EasyDB->safeQuery('INSERT INTO "te...', Array, 4, true)
#2 php shell code(1): ParagonIE\EasyDB\EasyDB->insert('test', Array)
#3 {main}
  thrown in /usr/src/app/vendor/paragonie/easydb/src/EasyDB.php on line 641
```

**Comment by paragonie-scott** [comment]
The only separator we used was `.` which I thought was standard. SQLite allows `/` too? We might need to add a driver-specific exception for them.

**Comment by paragonie-scott** [comment]
It turns out: this isn't a separator, but SQLite allows forward slashes in identifiers.

**Comment by ponchofiesta** [comment]
Yes, it is a sign in the identifier. I only told about allowSeperator because it changed the behaviour. I couldn‘t find any documentation about it. EasyDB simply needs quoting for field identifiers. But to bring this problem down a little bit: Doctrine DBAL and 2 other small wrapper libraries can‘t handle this to. I did it now in plain PDO. But support for it would be great.

**Comment by paragonie-scott** [comment]
This will be fixed in #53

**Comment by paragonie-scott** [comment]
The next release (`v2.4.0`) will support this. Thanks for reporting it. 👍

**Comment by ponchofiesta** [comment]
Thanks for fixing it. Works for me.
