### ISSUE TITLE
Fetch mode is always FETCH_ASSOC

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/easydb#49]
Given the following setup:

```php
$options = [
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_OBJ
];
$db = \ParagonIE\EasyDB\Factory::create(
    $dsn,
    $username,
    $password
    $options
);
```

...we should respect the configured setting in a backwards-compatible way. (i.e. if explicitly passed, use that, otherwise, default to FETCH_ASSOC like we always do).

**Comment by shadowhand** [comment]
Isn't this in conflict with being fully type safe? For example, we cannot be sure that the return type from `fetchRow` will be an array with this change, as it might be an object if `PDO::FETCH_OBJ` is used.

**Comment by paragonie-scott** [comment]
Not necessarily. We will have to forego the return type declaration, though.

**Comment by shadowhand** [comment]
This seems like a mistake to me. What benefit is there to `FETCH_OBJ`? A typeless object is no better than a typeless array, imo.

**Comment by shadowhand** [comment]
At least with `FETCH_ASSOC` we know that all row selects will be an array.

**Comment by paragonie-scott** [comment]
Some people prefer to use PDO that way, but want the convenience methods EasyDB offers. This encourages them to not write their own hacks.
