### ISSUE TITLE
Multiple issues with EasyDB::insertGet

### ISSUE THREAD

**Issue by duskwuff** [paragonie/easydb#57]
The documentation for this function doesn't clearly explain its purpose. As best I can tell, it's intended to insert a row, then return its auto-increment ID. (Is this accurate?)

The straightforward way of doing this would be to use `PDO::lastInsertId()`, which is already exposed as `EasyDB::lastInsertId()`. However, `insertGet()` instead takes the roundabout approach of performing a follow-up SELECT using every column in the inserted data as a condition. This is likely to result in strange query plans, especially in tables with many indices. Under some contrived circumstances (e.g, a table with an index covering a low-cardinality column and a monotonically decreasing column), the resulting plan may end up scanning a large portion of the table before finding the intended row.

If `insertGet()` is called with a `$map` which matches data which already exists in the table and `$field` is *not* the auto-increment column, the value returned by `insertGet()` may correspond to a different row than the one which was most recently inserted. (Under the mysql and pgsql drivers, it will be the largest value which exists in a matching row; under other drivers, it will be an arbitrary value.)

If `$map` is empty, the SELECT will fail entirely, as the WHERE clause is empty.

**Comment by paragonie-scott** [comment]
> The straightforward way of doing this would be to use `PDO::lastInsertId()`, which is already exposed as `EasyDB::lastInsertId()`. However, `insertGet()` instead takes the roundabout approach of performing a follow-up SELECT using every column in the inserted data as a condition. This is likely to result in strange query plans, especially in tables with many indices. Under some contrived circumstances (e.g, a table with an index covering a low-cardinality column and a monotonically decreasing column), the resulting plan may end up scanning a large portion of the table before finding the intended row.

Unfortunately, `lastInsertId()` isn't reliable across all database drivers. From [the manual](http://php.net/manual/en/pdo.lastinsertid.php):

>  This method may not return a meaningful or consistent result across different PDO drivers, because the underlying database may not even support the notion of auto-increment fields or sequences.

If you know your driver does support it, you *can* just do this:

```php
$easydb->insert('table, [
    'field' => $value,
    'field2' => 12345
]);
$lastInsertId = $easydb->lastInsertId();
```

> If `$map` is empty, the SELECT will fail entirely, as the WHERE clause is empty.

Interesting. I'll definitely look into building a fix for this ASAP.

**Comment by duskwuff** [comment]
> Unfortunately, `lastInsertId()` isn't reliable across all database drivers.

True… but are there actually any databases supported by PDO that support auto-increment columns, but whose PDO drivers don't support `lastInsertId()`? I'm not certain they exist, nor that they're worth including support for. (It certainly works fine for MySQL, PostgreSQL, and SQLite, and I believe it works for MSSQL as well.)

Having `$easydb->insert()` return the last insert ID directly seems like it'd be a more sane interface.

**Comment by shadowhand** [comment]
@duskwuff yes, Postgres. The only reliable way to fetch the last insert ID with postgres is with an [`INSERT ... RETURNING ...`](https://www.postgresql.org/docs/9.6/static/sql-insert.html#AEN88766) statement.

**Comment by paragonie-scott** [comment]
`EasyDB::insertGet()` no longer allows an empty array of keys/values.

**Comment by paragonie-scott** [comment]
Since `insert()` is already defined to return a boolean value in 2.x, we could add an `insertReturnId()` that shortcuts the code snippet I included above without having to bump the major version.
