### ISSUE TITLE
But can easyDB be more sugary

### ISSUE THREAD

**Issue by aolko** [paragonie/easydb#64]
...like [meekrodb](http://meekro.com/quickstart.php)?

**Comment by shadowhand** [comment]
If you are looking for a query builder there are plenty of options; [latitude](https://github.com/shadowhand/latitude) and [aura.sqlquery](https://github.com/auraphp/Aura.SqlQuery) to name just two.

**Comment by paragonie-scott** [comment]
I've added links to both to the README, in case anyone wants to go down that route. I was originally going to write my own, but it looks like Latitude does exactly what I wanted to write.
