### ISSUE TITLE
How to run a statement/query without parameters?

### ISSUE THREAD

**Issue by LivraghiFrancesco** [paragonie/easydb#80]
I have this query:
`SELECT MAX(fieldName) AS maxValue FROM myTable;`

I'll try to fetch the single column:
`$maxValue = $db->cell( "SELECT MAX(fieldName) AS maxValue FROM myTable;",null);`

The `public function single(...` returns the error  HY093: Invalid parameter number: parameter was not defined.

How to run a PDO:statement without parameters?
Thanks in advance, Francesco

**Comment by paragonie-scott** [comment]
```
$maxValue = $db->cell( "SELECT MAX(fieldName) AS maxValue FROM myTable;");
```

Just omit them.

**Comment by LivraghiFrancesco** [comment]
It works, thank you!
