### ISSUE TITLE
Thows 'Only one-dimensional arrays are allowed' usin 1D array

### ISSUE THREAD

**Issue by rozdol** [paragonie/easydb#85]
```php
$rows = $db->run('SELECT ?', 1); // works
$rows = $db->run('SELECT ?', [1]); // Error
```
How to run select query with multiple bind variables?
for example:
```sql
SELECT
    id,
    username AS "nam",
    email AS "user_email",
    COUNT(*) AS "some_count"
FROM
    "users"
WHERE
    username = :_1_
    AND surname = :_2_
GROUP BY
    id,
    email
```

**Comment by shadowhand** [comment]
[Use EasyStatement](https://github.com/paragonie/easydb#generate-dynamic-query-conditions) for `WHERE` conditions and use [use the helper](https://github.com/paragonie/easydb#variable-number-of-in-arguments) to generate a list for multiple arguments.

**Comment by rozdol** [comment]
Thank you for prompt reply. It really works with `safeQuery()`. 
The SQL statement I am generating with [Aura.SqlQuery](https://github.com/auraphp/Aura.SqlQuery).

**Comment by paragonie-scott** [comment]
The next release should eliminate confusion entirely.
