### ISSUE TITLE
Informix not escape column and table name

### ISSUE THREAD

**Issue by LivraghiFrancesco** [paragonie/easydb#87]
I'm working with an Informix DB engine and I discovered that, in the CRUD operations, Informix generates an error if the colums and table names are escaped. I have updated the  `function escapeIdentifier(...)`  as shown below:

```
public function escapeIdentifier(string $string, bool $quote = true): string
{
....
 if ($quote) {
            switch ($this->dbEngine) {
                case 'mssql':
                    return '[' . $str . ']';
                case 'mysql':
                    return '`' . $str . '`';
                case 'informix':
                    return $str;                   
                default:
                    return '"' . $str . '"';
            }
        }
        return $str;
}
```
The solution it is under test and it seems work perfectly!

Best regards
Francesco

**Comment by SignpostMarv** [comment]
Seems like you need to explicitly enable delimiters with informix ? 

[Via stackoverflow](https://stackoverflow.com/questions/37487548/how-do-i-escape-reserved-words-used-as-identifier-in-informix):
> DELIMIDENT: When set to Y, specifies that strings set off by double quotation marks are delimited identifiers
~ [IBM Knowledgebase](https://www.ibm.com/support/knowledgecenter/en/SSGU8G_12.1.0/com.ibm.jdbc_pg.doc/ids_jdbc_040.htm)
