### ISSUE TITLE
is this a redundant is1DArray() check?

### ISSUE THREAD

**Issue by SignpostMarv** [paragonie/easydb#9]
Haven't had time to write tests at work, started fleshing out the tests today & noticed something- not 100% sure, but is the second EasyDB::is1DArray() check in EasyDB::insertMany() redundant?

- [First Check](https://github.com/paragonie/easydb/blob/0b5c98753812c64bf256db4b0d33d39d59b2afbd/src/EasyDB.php#L389)
- [Second Check](https://github.com/paragonie/easydb/blob/0b5c98753812c64bf256db4b0d33d39d59b2afbd/src/EasyDB.php#L425)

**Comment by paragonie-scott** [comment]
Yes, I'll file a ticket with the Department of Redundancy Department.

**Comment by paragonie-scott** [comment]
I believe this is fixed now. :)
