### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by anant-shah** [paragonie/easydb#90]
I can connect to my database using straight PDO. But, cannot connect using easydb. It gives PDO connection error. Check username & password. I am using V2.0.0 with Php 7.2. In addition, the error displays username and password and would like to suppress those.

**Comment by paragonie-scott** [comment]
What does your code look like (with username/password censored) when you instantiate EasyDB?

**Comment by anant-shah** [comment]
<?php

declare(strict_types = 1);

require 'vendor/autoload.php';

$db = \ParagonIE\EasyDB\Factory::create('mysql:host=localhost;dbname=temp;', 'root', 'xxxxxx');

/* $db = new PDO('mysql:host=localhost;dbname=temp;', 'root', 'xxxxxx'); */
echo true;

?>

**Comment by anant-shah** [comment]
declare(strict_types = 1);

require 'vendor/autoload.php';


$db = \ParagonIE\EasyDB\Factory::create('mysql:host=localhost;dbname=temp;', 'root', 'xxxxxx');

// $db = new PDO('mysql:host=localhost;dbname=temp;', 'root', 'xxxxxx');
echo true;

**Comment by anant-shah** [comment]
![code_snippet](https://user-images.githubusercontent.com/35120412/47127183-ecf4b480-d240-11e8-951d-369311cd64fa.PNG)
![easydb error](https://user-images.githubusercontent.com/35120412/47127184-ecf4b480-d240-11e8-9fe8-24ec7f74e999.png)
![straightpdo](https://user-images.githubusercontent.com/35120412/47127185-ecf4b480-d240-11e8-8cba-efb3a955428b.PNG)

**Comment by paragonie-scott** [comment]
Interesting. I'll look through the Factory class in the morning.

In the meantime, if you do `$db = new EasyDB(new PDO(/* ... */));` you can solve your immediate problem.

**Comment by anant-shah** [comment]
When I ran the following code:
declare(strict_types = 1);
require 'vendor/autoload.php';
$db = new EasyDB(new PDO('mysql:host=localhost;dbname=temp;', 'root', 'xxxx'));
echo true;
I get the following error:
Fatal error: Uncaught Error: Class 'EasyDB' not found in D:\WAMP\Apache24\htdocs\dbdemo\dbdemo.php:14 Stack trace: #0 {main} thrown in D:\WAMP\Apache24\htdocs\dbdemo\dbdemo.php on line 14

See attached for directory and composer.json 
![1](https://user-images.githubusercontent.com/35120412/47189327-cee68d00-d2f0-11e8-818d-54e82df3ad29.PNG)
![2](https://user-images.githubusercontent.com/35120412/47189328-cee68d00-d2f0-11e8-8ff9-15e2bf2d9894.PNG)
![3](https://user-images.githubusercontent.com/35120412/47189329-cee68d00-d2f0-11e8-951e-c96d69e46e6e.PNG)

**Comment by paragonie-scott** [comment]
You need to import the namespace or use a fully qualified class name.

```diff
+ use ParagonIE\EasyDB\EasyDB;
// ...
$db = new EasyDB(new PDO('mysql:host=localhost;dbname=temp;', 'root', 'xxxx'));
```

or

```diff
- $db = new EasyDB(new PDO('mysql:host=localhost;dbname=temp;', 'root', 'xxxx'));
+ $db = new ParagonIE\EasyDB\EasyDB(new PDO('mysql:host=localhost;dbname=temp;', 'root', 'xxxx'));
```

**Comment by paragonie-scott** [comment]
It's been a while. If this hasn't been resolved, please let me know and I'll reopen.
