### ISSUE TITLE
Multiple IN's

### ISSUE THREAD

**Issue by ParadiseStudios** [paragonie/easydb#91]
Would like to be able to use multiple IN's in a WHERE statement without errors about only one dimensional arrays being allowed.

```
$states[] = (IL, IN, VA);
run("SELECT id FROM states WHERE state IN (?)", $states);
```

The only way to achieve this is to do the following, which leaves one open to injection attacks, right?

`run("SELECT id FROM states WHERE state IN (" . implode(',', $states) . ")");`

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/easydb#variable-number-of-in-arguments

**Comment by ParadiseStudios** [comment]
Sorry, I guess I must be blind today. I still get the same error though, "Only one-dimensional arrays are allowed."

```
$statement = \ParagonIE\EasyDB\EasyStatement::open()->in('state IN (?*)', $states);
$this->_db->run('SELECT id FROM states WHERE ' . $statement . '', $statement->values());
print_r($statement);

ParagonIE\EasyDB\EasyStatement Object
(
    [parts:ParagonIE\EasyDB\EasyStatement:private] => Array
        (
            [0] => Array
                (
                    [type] => AND
                    [condition] => state IN (?, ?)
                    [values] => Array
                        (
                            [0] => 16
                            [1] => 3
                        )

                )

        )

    [parent:ParagonIE\EasyDB\EasyStatement:private] => 
)
```

**Comment by paragonie-scott** [comment]
This isn't the first time someone has been tripped up by this, so I've added it to the README as well. https://github.com/paragonie/easydb/commit/76094ff093d6a3ee1ab3a9a6fc133cb6dbd54327

https://github.com/paragonie/easydb#only-one-dimensional-arrays-are-allowed

**Comment by ParadiseStudios** [comment]
Thank you @paragonie-scott !
I was able to have both queries run successfully. The splat operator worked right away. I had to modify the `safeQuery()` to make it work because I had other parameters that needed to be passed through. If you had to use one over the other for security, which one would you choose? Also, should I be using `safeQuery()` over `run()` more often?

```
$statement = \ParagonIE\EasyDB\EasyStatement::open()->orIN('restriction IN (?*)', $restrictions);
$params = $statement->values();
array_unshift($params, $this->getStateID($state));
$this->_db->safeQuery('SELECT id FROM states WHERE state = ? AND ' . $statement . '', $params);

vs

$statement = \ParagonIE\EasyDB\EasyStatement::open()->orIN('restriction IN (?*)', $restrictions);
$this->_db->run('SELECT id FROM states WHERE state = ? AND ' . $statement . '', $this->getStateID($state), ...$statement->values());
```

**Comment by paragonie-scott** [comment]
They're equivalent in terms of security.

Use whichever endpoint you're more comfortable with. `safeQuery()` is being updated (thanks @SignpostMarv) in the next release to reduce confusion.
