### ISSUE TITLE
Error Management

### ISSUE THREAD

**Issue by DLX23** [paragonie/easydb#95]
if i try to get a row that doesnt exist, follow error will show on page:
Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'order clause' in /var/www/

how can i catch that error so that the visitor can't see this error, and i can show own error message and log this easydb error to my own logfile ?

**Comment by shadowhand** [comment]
Use [try ... catch][1]:

```php
use PDOException;

try {
    /* the query */
} catch (PDOException $e) {
    /* your logging */
}
```

[1]: http://php.net/manual/en/language.exceptions.php
