### ISSUE TITLE
query re: paragonie/corner

### ISSUE THREAD

**Issue by SignpostMarv** [paragonie/easydb#96]
If one were to tinker with the exceptions thrown by easydb, would it be better to change `ParagonIE\EasyDB\Exception\ExceptionInterface` to extend from `ParagonIE\Corner\CornerInterface`, or extend the exception classes & implement `CornerInterface` there ?

**Comment by paragonie-scott** [comment]
Hi Marv,

I'm just cleaning up open tickets that have been fixed right now. Is there still anything left to do on this? I don't want to close it if there still is. :)

Thanks,
Scott

**Comment by SignpostMarv** [comment]
this ticket was originally a query about corner's implementation, so if you're happy with the implementation here then I'm happy? :)
